config/routes.rb
require 'api_constraints'

Rails.application.routes.draw do
  devise_for :users
  root :to => 'pages#home'
  get 'prueba' => 'pages#prueba'

  # Users Controller
  resources :users
  get 'patients' => 'users#patients'
  post 'new_patient' => 'users#new_patient'
  put 'set_inactive/:id' => 'users#set_inactive'

  # API V1
  namespace :api, defaults: {format: 'json'} do
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: true) do
      resources :users
    end
  end
end

app/models/clinic.rb
class Clinic < ActiveRecord::Base
  has_many :users

  def patients
    users.where(role: 'patient')
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :clinic
  validates :nutritionist_id, :presence => true, if: :patient?

  validates :email, uniqueness: true
  validates :email, :presence => true
  validates :first_name, :presence => true
  validates :last_name, :presence => true

  def patients
    return nil if role == 'patient'
    User.where(nutritionist_id: id, active: true).order(:first_name)
  end

  def full_name
    first_name+" "+last_name
  end

  def patient?
    role == "patient"
  end
end

app/controllers/api/v1/users_controller.rb
module Api
	module V1
		class UsersController < ApplicationController
			respond_to :json

      def create
        clean_params params
        respond_with User.create(user_params)
      end

      def clean_params params
        if params[:role] == 'patient'
          params[:clinic_id] = current_user.clinic_id
          params[:password] = SecureRandom.hex(4)
        end
      end

      def user_params
        params.permit(:first_name, :last_name, :email,
        :phone, :address, :role, :clinic_id, :password)
      end

    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  def home

  end

  def prueba

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :verify_authenticity_token, :only => :new_patient
  def patients
    @patients = current_user.patients
  end

  def new_patient
    params[:clinic_id] = current_user.clinic_id
    params[:password] = SecureRandom.hex(4)
    params[:nutritionist_id] = current_user.id
    User.create(user_params)
    redirect_to :back
  end

  def user_params(params=params)
    params.permit(:first_name, :last_name, :email,
    :phone, :address, :role, :clinic_id, :password, :role, :nutritionist_id,
    :active)
  end

  def edit
    @user = User.find(params[:id])
  end

  def set_inactive
    user = User.find(params[:id])
    user.update_attributes(active: false)
    redirect_to patients_path, notice: 'Paciente eliminado'
  end

  def update
    user = User.find(params[:id])
    if user.update(user_params(params[:user]))
      redirect_to(patients_path, notice: 'Paciente modificado con éxito')
    else
      redirect_to(:back, notice: 'Ocurrió un error al intentar modificar el registro')
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_footer.html.erb
<footer class="page-footer">
  <div class="footer-copyright">
    <div class="container">
    © 2016 Todos lo derechos reservados
    <a class="grey-text text-lighten-4 right" href="https://www.pacoguevara.com">
			Desarrollado por Paco Guevara
		</a>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav>
  <div class="nav-wrapper">
    <a class="brand-logo" href="/">Kino</a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li><%= link_to "Iniciar Sesión", new_user_session_path() %></li>
      <li><%= link_to "Crear cuenta", new_user_registration_path() %></li>
    </ul>
  </div>
</nav>

app/views/layouts/_header_logged.html.erb
<nav>
  <div class="nav-wrapper">
    <a class="brand-logo" href="/">Kino</a>
    <ul id="nav-mobile" class="right hide-on-med-and-down">
      <li class=""><a href="<%= patients_path() %>">Pacientes</a></li>
      <li class=""><a href="#">Citas</a></li>
      <li class=""><a href="#">Comidas</a></li>
      <li class="dropdown">
        <a href="#" class="dropdown-button" data-activates='dropdown1'><%= current_user.email %> <span class="caret"></span></a>
        <ul id='dropdown1' class='dropdown-content'>
          <li><%= link_to "Editar cuenta", edit_user_registration_path() %></li>
          <li><a href="#">Configuración</a></li>
          <li role="separator" class="divider"></li>
          <li><%= link_to "Cerrar Sesión", destroy_user_session_path(), method: 'delete' %></li>
        </ul>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kino</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/css/materialize.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>
  <script src="https://use.fontawesome.com/e516f4fb94.js"></script>
</head>
<body>
  <div class="">
    <% flash.each do |name,msg| %>
      <script type="text/javascript">
        Materialize.toast("<%= msg %>", 4000)
      </script>
		<% end %>
    <% if user_signed_in? %>
      <%= render 'layouts/header_logged'%>
    <% else %>
      <%= render 'layouts/header'%>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer'%>
  </div>
</body>
</html>

app/views/pages/prueba.html.erb
Esto es una prueba!

app/views/users/_new_patient_form.html.erb
<!-- Modal Structure -->
<div id="new-patient-form" class="modal">
  <div class="modal-content">
    <h4>Nuevo paciente</h4>
    <div class="row">
      <form class="" action="<%= new_patient_path() %>" method="post">
        <div class="row">
          <div class="input-field col m6 s12">
            <label for="">Nombre</label><br />
            <input type="text" name="first_name" id="first_name" class="validate" data-validation="required">
          </div>
          <div class="input-field col m6 s12">
            <label for="">Apellido</label><br />
            <input type="text" name="last_name" id="last_name" class="validate" data-validation="required">
          </div>
        </div>
        <div class="row">
          <div class="input-field col m6 s12">
            <label for="">Email</label><br />
            <input type="email" name="email" id="email" class="validate" data-validation="required email">
          </div>
          <div class="input-field col m6 s12">
            <label for="">Teléfono</label><br />
            <input type="text" name="phone" id="phone" class="validate">
          </div>
        </div>
        <div class="row">
          <div class="input-field col s12">
            <label for="">Dirección</label><br />
            <input type="text" name="address" id="address" class="validate">
            <input type="hidden" name="role" id="role" value="patient">
          </div>
        </div>
        <div class="row">
          <div class="actions col s12">
            <button type="submit" name="button" class="btn cyan waves-effect waves-light right">Guardar</button>
          </div>
        </div>
      </form>
    </div>
  </div>
  <div class="modal-footer">
    <a href="#!" class=" modal-action modal-close waves-effect waves-green btn-flat">Cancelar</a>
  </div>
</div>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.3.26/jquery.form-validator.min.js"></script>
<script type="text/javascript">
  $.validate({
    lang: 'es'
  });
</script>

app/views/users/edit.html.erb
<div class="basic-form section">
  <div class="row">
    <div class="col s12 m12 l6 offset-l3">
      <div class="card-panel">
        <h4>Editar paciente</h4>
        <div class="row">
          <%= form_for @user do |f| %>
            <div class="row">
              <div class="input-field col s12">
                <%= f.label :first_name, "Nombre" %><br />
                <%= f.text_field :first_name, autofocus: true, class: "validate", 'data-validation' => "required" %>
              </div>
            </div>

            <div class="row">
              <div class="input-field col s12">
                <%= f.label :last_name, "Apellido" %><br />
                <%= f.text_field :last_name, autofocus: true, class: "validate", 'data-validation' => "required" %>
              </div>
            </div>

            <div class="row">
              <div class="input-field col s12">
                <%= f.label :email, "Correo electrónico" %><br />
                <%= f.email_field :email, autofocus: true, class: "validate", 'data-validation' => "required" %>
              </div>
            </div>

            <div class="row">
              <div class="input-field col s12">
                <%= f.label :phone, "Teléfono" %><br />
                <%= f.text_field :phone, autofocus: true, class: "validate" %>
              </div>
            </div>

            <div class="row">
              <div class="input-field col s12">
                <%= f.label :address, "Dirección" %><br />
                <%= f.text_field :address, autofocus: true, class: "validate" %>
              </div>
            </div>

            <div class="row">
              <div class="col m6 s12">
                <%= link_to 'Eliminar', "/set_inactive/#{@user.id}",
            data: {:confirm => 'Este seguro que desea eliminar al paciente?'}, :method => :put %>
              </div>
              <div class="actions col m6 s12">
                <%= f.submit "Guardar", class: "btn cyan waves-effect waves-light right" %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<script src="//cdnjs.cloudflare.com/ajax/libs/jquery-form-validator/2.3.26/jquery.form-validator.min.js"></script>
<script type="text/javascript">
  $.validate({
    lang: 'es'
  });
</script>

app/views/users/patients.html.erb
<div class="row">
  <div class="col m3 offset-m5 s8 offset-s2">
    <h3>Pacientes</h3>
  </div>
  <div class="col m2">
    <a class="btn-floating btn-large waves-effect waves-light red add-patient btn modal-trigger" href="#new-patient-form">
      <i class="fa fa-plus"></i>
    </a>
  </div>
</div>
<section id="patients-container">
  <% if @patients.blank? %>
    <div class="row">
      <div class="col m3 offset-m4 s12">
        <i>No ha agregado ningún paciente aún</i>
      </div>
    </div>
  <% else %>
    <div class="row">
      <% @patients.each do |patient| %>
        <div class="col s4 m2">
          <div class="card">
            <div class="card-image">
              <%= image_tag 'user.png', style: "width: 100%" %>
              <span class="card-title"><%= patient.full_name %></span>
            </div>
            <div class="card-content">
              <p>I am a very simple card. I am good at containing small bits of information.</p>
            </div>

            <div class="card-action">
              <%= link_to 'Eliminar', "/set_inactive/#{patient.id}",
            data: {:confirm => 'Este seguro que desea eliminar al paciente?'}, :method => :put %>
              <a href="<%= edit_user_path(patient.id) %>">Editar</a>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
</section>
<%= render "new_patient_form" %>
<script type="text/javascript">
$(document).ready(function() {
  Patient.init();
});
</script>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>